on: [push]

name: CI

jobs:
  build_and_test:
    name: tree_sim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features